<?php if(isset($_SESSION['auth'])){ ?>
			<?php
				$listCartItems = $this->view->listCartItems;
				if(count($listCartItems) > 0){
			?>
<script type="text/javascript">
	var e = document.getElementById('cart');
	e.setAttribute("class", "sale-noti");
	document.getElementById('page-title').innerHTML = 'Cart';
</script>
<!-- Title Page -->
<section class="bg-title-page p-t-40 p-b-50 flex-col-c-m" style="background-image: url(images/cart_background.png);">
	<h2 class="l-text2 t-center">
		Cart 🛒
	</h2>
</section>

<!-- Cart -->
<section class="cart bgwhite p-t-70 p-b-100">
	<div class="container">
		<!-- Cart item -->
		<div class="container-table-cart pos-relative">
			<div class="wrap-table-shopping-cart bgwhite">
				<table class="table-shopping-cart" id="table-cart">
					<tr class="table-head">
						<th class="column-1"></th>
						<th class="column-2">Games</th>
						<th class="column-3">Price</th>
						<th class="column-4 p-l-70">Quantity</th>
						<th class="column-5">Total</th>
					</tr>

					<?php
						$total = 0;
						foreach($listCartItems as $rows){
					?>
						<tr class="table-row">
							<td class="column-1">
								<div class="cart-img-product b-rad-4 o-f-hidden" onclick="removeCartItem_<?php echo $rows->game_id; ?>()">
									<img class="cart-image" src="<?php echo $rows->image_720_932; ?>" alt="IMG-GAME">
								</div>
							</td>
							<td class="column-2"><span class="game-id" hidden="true"><?php echo $rows->game_id; ?></span><a href="?action=game-detail&id=<?php echo $rows->game_id; ?>" class="game-title"><?php echo $rows->title; ?></a></td>
							<td class="column-3"><?php echo number_format($rows->game_price, 0, ",", ".")." VND"; ?></td>
							<td class="column-4" align="center">
								<div class="flex-w bo5 of-hidden w-size17">
									<button class="btn-num-product-down color1 flex-c-m size7 bg8 eff2">
										<i class="fs-12 fa fa-minus" aria-hidden="true"></i>
									</button>

									<input class="size8 m-text18 t-center num-product" id="quantity<?php echo $rows->game_id; ?>" type="number" name="num-product1" value="<?php echo $rows->quantity; ?>" onchange="myfunction<?php echo $rows->game_id; ?>()">

									<button class="btn-num-product-up color1 flex-c-m size7 bg8 eff2">
										<i class="fs-12 fa fa-plus" aria-hidden="true"></i>
									</button>
									<span id="game-id-to-update" hidden><?php echo $rows->game_id; ?></span>
									<span id="account-id-to-update" hidden><?php echo $_SESSION['auth']->id; ?></span>
								</div>
							</td>
							<td class="column-5"><?php echo number_format($rows->game_price*$rows->quantity, 0, ",", ".")." VND"; ?></td>
						</tr>
						<script type="text/javascript">
							function removeCartItem_<?php echo $rows->game_id; ?>(){
								var game_id = <?php echo $rows->game_id; ?>;
								var title = <?php echo "'".str_replace("'", "\'", $rows->title)."'"; ?>;
								var account_id = <?php echo $_SESSION['auth']->id; ?>;
								ajaxRemoveCartItem(game_id, account_id);
							}
						</script>
						<script type="text/javascript">
							function myfunction<?php echo $rows->game_id; ?>(){
								var quantity = Number($("#quantity<?php echo $rows->game_id; ?>").val());
								if(quantity < 1){
									$("#quantity<?php echo $rows->game_id; ?>").val('');
									swal("YOU MUST ENTER", "a number greater than 0!", "warning");
								} else {
									var title = '<?php echo str_replace("'", "\'", $rows->title); ?>';
									var game_id = <?php echo $rows->game_id; ?>;
									var account_id = <?php echo $_SESSION['auth']->id; ?>;
									$.ajax({
					          type: 'GET',
					          url: "",
					          data: "action=update-cart-item&game_id=" + game_id + "&quantity=" + quantity + "&account_id=" + account_id,
					          success: function() {
					            swal(quantity + " key of " + title, "is updated to cart !", "success");
					          }
					        });
								}
							}
						</script>
					<?php
							$total += $rows->quantity * $rows->game_price;
						}
					?>
				</table>
			</div>
		</div>
		<div class="flex-w flex-sb-m p-t-25 p-b-25 bo8 p-l-35 p-r-60 p-lr-15-sm">
			<div class="size10 trans-0-4 m-t-10 m-b-10">
				<!-- Button -->
				<button class="flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4" onclick="updateCart()">
					Update Cart
				</button>
			</div>
		</div>
		<script type="text/javascript">
			function updateCart(){
				location.reload();
			}
		</script>

		<!-- Total -->
		<div class="bo9 w-size18 p-l-40 p-r-40 p-t-30 p-b-38 m-t-30 m-r-0 m-l-auto p-lr-15-sm">
			<h5 class="m-text20 p-b-24">
				Cart Totals
			</h5>

			<!--  -->
			<div class="flex-w flex-sb-m p-b-12">
				<span class="s-text18 w-size19 w-full-sm">
					Subtotal:
				</span>

				<span class="m-text21 w-size20 w-full-sm" id="subtotal">
					<?php echo number_format($total, 0, ",", ".")." VND"; ?>
				</span>
			</div>

			<!--  -->
			<div class="flex-w flex-sb bo10 p-t-15 p-b-20">
				<span class="s-text18 w-size19 w-full-sm">
					Coupon:
				</span>

				<div class="w-size20 w-full-sm">
					<span class="m-text21 w-size20 w-full-sm">
						- 0 VND
					</span><br><br>
				</div>
			</div>

			<!--  -->
			<div class="flex-w flex-sb-m p-t-26 p-b-30">
				<span class="m-text22 w-size19 w-full-sm">
					Total:
				</span>

				<span class="m-text21 w-size20 w-full-sm" id="total">
					<?php echo number_format($total, 0, ",", ".")." VND"; ?>
				</span>
			</div>

			<div class="size15 trans-0-4">
				<!-- Button -->
				<button class="flex-c-m sizefull bg1 bo-rad-23 hov1 s-text1 trans-0-4" onclick="redirectToCheckOut()">
					Proceed to Checkout
				</button>
				<script type="text/javascript">
					function redirectToCheckOut(){
						window.location.href = "?action=check-out";
					}
				</script>
			</div>
		</div>
	</div>
</section>
	<?php } else { ?>
		<script type="text/javascript">
			var e = document.getElementById('cart');
			e.setAttribute("class", "sale-noti");
			document.getElementById('page-title').innerHTML = 'Cart';
		</script>
		<section class="bg-title-page p-t-40 p-b-50 flex-col-c-m">
			<h2 class="l-text2 t-center" style="color: #555555;">
				There are no items in the cart 🛒
			</h2>
		</section>
	<?php } ?>
<?php } else { ?>
	<script type="text/javascript">
		var e = document.getElementById('cart');
		e.setAttribute("class", "sale-noti");
		document.getElementById('page-title').innerHTML = 'Cart';
	</script>
	<section class="bg-title-page p-t-40 p-b-50 flex-col-c-m">
		<h2 class="l-text2 t-center" style="color: #555555;">
			You must login to use cart 🛒
		</h2>
	</section>
<?php } ?>