<?php
  $listFiveNewGames = $this->view->listFiveNewGames;
  $listEightNewGames = $this->view->listEightNewGames;
  //Debug
  // echo "<pre>";
  // print_r($listFiveNewGames);
  // echo "</pre>";
?>
<script type="text/javascript">
  var e = document.getElementById('home');
  e.setAttribute("class", "sale-noti");
</script>
<!-- Slide1 -->
  <section class="slide1">
    <div class="wrap-slick1">
      <div class="slick1">
        <div class="item-slick1 item1-slick1" style="background-image: url(public/images/slide_gta_v_2.jpg);">
          <div class="wrap-content-slide1 sizefull flex-col-c-m p-l-15 p-r-15 p-t-150 p-b-170">
            <span class="caption1-slide1 m-text1 t-center animated visible-false m-b-15" data-appear="fadeInDown">
              Grand Theft Auto V: Premium Edition
            </span>

            <h2 class="caption2-slide1 xl-text1 t-center animated visible-false m-b-37" data-appear="fadeInUp">
              Available Free
            </h2>

            <div class="wrap-btn-slide1 w-size1 animated visible-false" data-appear="zoomIn">
              <!-- Button -->
              <a href="?action=game-detail&id=4" class="flex-c-m size2 bo-rad-23 s-text2 bgwhite hov1 trans-0-4">
                Get It Now
              </a>
            </div>
          </div>
        </div>
        <div class="item-slick1 item2-slick1" style="background-image: url(public/images/slide_gta_v_1.jpg);"></div>
        <div class="item-slick1 item3-slick1" style="background-image: url(public/images/slide_gta_v_3.jpg);"></div>
      </div>
    </div>
  </section>

  <!-- Banner -->
  <section class="banner bgwhite p-t-40 p-b-40">
    <div class="container">
      <div class="row">
        <div class="col-sm-10 col-md-8 col-lg-4 m-l-r-auto">
          <!-- block1 -->
          <div class="block1 hov-img-zoom pos-relative m-b-30">
            <img src="<?php echo $listFiveNewGames[0]->image_720_932; ?>" alt="IMG-BENNER">

            <div class="block1-wrapbtn w-size2">
              <!-- Button -->
              
              <a href="?action=game-detail&id=<?php echo $listFiveNewGames[0]->id; ?>" class="flex-c-m size2 m-text2 bg3 hov1 trans-0-4">
                <?php echo $listFiveNewGames[0]->short_name; ?>
              </a>
            </div>
          </div>

          <!-- block1 -->
          <div class="block1 hov-img-zoom pos-relative m-b-30">
            <img src="<?php echo $listFiveNewGames[1]->image_720_660; ?>" alt="IMG-BENNER">

            <div class="block1-wrapbtn w-size2">
              <!-- Button -->
              <a href="?action=game-detail&id=<?php echo $listFiveNewGames[1]->id; ?>" class="flex-c-m size2 m-text2 bg3 hov1 trans-0-4">
                <?php echo $listFiveNewGames[1]->short_name; ?>
              </a>
            </div>
          </div>
        </div>

        <div class="col-sm-10 col-md-8 col-lg-4 m-l-r-auto">
          <!-- block1 -->
          <div class="block1 hov-img-zoom pos-relative m-b-30">
            <img src="<?php echo $listFiveNewGames[2]->image_720_660; ?>" alt="IMG-BENNER">

            <div class="block1-wrapbtn w-size2">
              <!-- Button -->
              <a href="?action=game-detail&id=<?php echo $listFiveNewGames[2]->id; ?>" class="flex-c-m size2 m-text2 bg3 hov1 trans-0-4">
                <?php echo $listFiveNewGames[2]->short_name; ?>
              </a>
            </div>
          </div>

          <!-- block1 -->
          <div class="block1 hov-img-zoom pos-relative m-b-30">
            <img src="<?php echo $listFiveNewGames[3]->image_720_932; ?>" alt="IMG-BENNER">

            <div class="block1-wrapbtn w-size2">
              <!-- Button -->
              <a href="?action=game-detail&id=<?php echo $listFiveNewGames[3]->id; ?>" class="flex-c-m size2 m-text2 bg3 hov1 trans-0-4">
                <?php echo $listFiveNewGames[3]->short_name; ?>
              </a>
            </div>
          </div>
        </div>

        <div class="col-sm-10 col-md-8 col-lg-4 m-l-r-auto">
          <!-- block1 -->
          <div class="block1 hov-img-zoom pos-relative m-b-30">
            <img src="<?php echo $listFiveNewGames[4]->image_720_932; ?>" alt="IMG-BENNER">

            <div class="block1-wrapbtn w-size2">
              <!-- Button -->
              <a href="?action=game-detail&id=<?php echo $listFiveNewGames[4]->id; ?>" class="flex-c-m size2 m-text2 bg3 hov1 trans-0-4">
                <?php echo $listFiveNewGames[4]->short_name; ?>
              </a>
            </div>
          </div>

          <!-- block2 -->
          <div class="block2 wrap-pic-w pos-relative m-b-30">
            <img src="public/images/icons/bg-01.jpg" alt="IMG">

            <div class="block2-content sizefull ab-t-l flex-col-c-m">
              <h4 class="m-text4 t-center w-size3 p-b-8">
                View more new games
              </h4>

              <p class="t-center w-size4">
                Be the first to know about the latest game news and get exclu-sive offers
              </p>

              <div class="w-size2 p-t-25">
                <!-- Button -->
                <a href="#" class="flex-c-m size2 bg4 bo-rad-23 hov1 m-text3 trans-0-4">
                  View more
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- New Product -->
  <section class="newproduct bgwhite p-t-45 p-b-105">
    <div class="container">
      <div class="sec-title p-b-60">
        <h3 class="m-text5 t-center">
          Featured Products
        </h3>
      </div>

      <!-- Slide2 -->
      <div class="wrap-slick2">
        <div class="slick2">
          <?php foreach ($listEightNewGames as $rows) { ?>
          <div class="item-slick2 p-l-15 p-r-15">
            <!-- Block2 -->
            <div class="block2">
              <div class="block2-img wrap-pic-w of-hidden pos-relative block2-labelnew">
                <img src="<?php echo $rows->image_720_932; ?>" alt="IMG-PRODUCT">

                <div class="block2-overlay trans-0-4">
                  <a href="#" class="block2-btn-addwishlist hov-pointer trans-0-4">
                    <i class="icon-wishlist icon_heart_alt" aria-hidden="true"></i>
                    <i class="icon-wishlist icon_heart dis-none" aria-hidden="true"></i>
                  </a>

                  <div class="block2-btn-addcart w-size1 trans-0-4">
                    <!-- Button -->
                    <button class="flex-c-m size1 bg4 bo-rad-23 hov1 s-text1 trans-0-4">
                      Add to Cart
                    </button>
                  </div>
                </div>
              </div>

              <div class="block2-txt p-t-20">
                <a href="?action=game-detail&id=<?php echo $rows->id; ?>" class="block2-name dis-block s-text3 p-b-5">
                  <?php echo $rows->title; ?>
                </a>
                <span class="block2-id" hidden><?php echo $rows->id; ?></span>
                <span class="block2-price m-text6 p-r-5">
                  <?php echo number_format($rows->price, 0, ",", ".")." VND"; ?>
                </span>
              </div>
            </div>
          </div>
        <?php } ?>
        </div>
      </div>
    </div>
  </section>

  <!-- Banner2 -->
  <section class="banner2 bg5 p-t-55 p-b-55">
    <div class="container">
      <div class="row">
        <div class="col-sm-10 col-md-8 col-lg-6 m-l-r-auto p-t-15 p-b-15">
          <div class="hov-img-zoom pos-relative">
            <img src="images/ac_collection.jpg" alt="IMG-BANNER">

            <div class="ab-t-l sizefull flex-col-c-m p-l-15 p-r-15">
              <span class="m-text9 p-t-45 fs-20-sm">
                The Assassin
              </span>

              <h3 class="l-text1 fs-35-sm">
                Colection
              </h3>

              <a href="#" class="s-text4 hov2 p-t-20 ">
                View Collection
              </a>
            </div>
          </div>
        </div>

        <div class="col-sm-10 col-md-8 col-lg-6 m-l-r-auto p-t-15 p-b-15">
          <div class="bgwhite hov-img-zoom pos-relative p-b-20per-ssm">
            <img src="images/gta_v_saling.jpg" alt="IMG-BANNER">

            <div class="ab-t-l sizefull flex-col-c-b p-l-15 p-r-15 p-b-20">
              <div class="t-center">
                <a href="product-detail.html" class="dis-block s-text3 p-b-5" style="color: white;">
                  Grand Thief Auto: Premium Edition
                </a>

                <span class="block2-oldprice m-text7 p-r-5" style="color: #999999;">
                  $29.50
                </span>

                <span class="block2-newprice m-text8" style="color: white;">
                  $15.90
                </span>
              </div>

              <div class="flex-c-m p-t-44 p-t-30-xl">
                <div class="flex-col-c-m size3 bo1 m-l-5 m-r-5">
                  <span class="m-text10 p-b-1 days" style="color: white;">
                    2
                  </span>

                  <span class="s-text5">
                    days
                  </span>
                </div>

                <div class="flex-col-c-m size3 bo1 m-l-5 m-r-5">
                  <span class="m-text10 p-b-1 hours" style="color: white;">
                    04
                  </span>

                  <span class="s-text5">
                    hrs
                  </span>
                </div>

                <div class="flex-col-c-m size3 bo1 m-l-5 m-r-5">
                  <span class="m-text10 p-b-1 minutes" style="color: white;">
                    32
                  </span>

                  <span class="s-text5">
                    mins
                  </span>
                </div>

                <div class="flex-col-c-m size3 bo1 m-l-5 m-r-5">
                  <span class="m-text10 p-b-1 seconds" style="color: white;">
                    05
                  </span>

                  <span class="s-text5">
                    secs
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>


  <!-- Blog -->
  <section class="blog bgwhite p-t-94 p-b-65">
    <div class="container">
      <div class="sec-title p-b-52">
        <h3 class="m-text5 t-center">
          News
        </h3>
      </div>

      <div class="row">
        <div class="col-sm-10 col-md-4 p-b-30 m-l-r-auto">
          <!-- Block3 -->
          <div class="block3">
            <a href="blog-detail.html" class="block3-img dis-block hov-img-zoom">
              <img src="images/news_1.jpg" alt="IMG-BLOG">
            </a>

            <div class="block3-txt p-t-14">
              <h4 class="p-b-7">
                <a href="blog-detail.html" class="m-text11">
                  Need for Speed Heat: Cross-Play to Be Added in Game's Final Update, First EA Game to Do So
                </a>
              </h4>

              <span class="s-text6">By</span> <span class="s-text7">Pyl Walker ✔</span>
              <span class="s-text6">on</span> <span class="s-text7" id="news-date-3"></span>
              <p class="s-text8 p-t-16">
                More details about the franchise to come during EA Play Live.
              </p>
            </div>
          </div>
        </div>

        <div class="col-sm-10 col-md-4 p-b-30 m-l-r-auto">
          <!-- Block3 -->
          <div class="block3">
            <a href="blog-detail.html" class="block3-img dis-block hov-img-zoom">
              <img src="images/news_2.jpg" alt="IMG-BLOG">
            </a>

            <div class="block3-txt p-t-14">
              <h4 class="p-b-7">
                <a href="blog-detail.html" class="m-text11">
                  PS5 Reveal Event Officially Rescheduled for June 11
                </a>
              </h4>

              <span class="s-text6">By</span> <span class="s-text7">Pyl Walker ✔</span>
              <span class="s-text6">on</span> <span class="s-text7" id="news-date-2"></span>

              <p class="s-text8 p-t-16">
                See the future on June 11.
              </p>
            </div>
          </div>
        </div>

        <div class="col-sm-10 col-md-4 p-b-30 m-l-r-auto">
          <!-- Block3 -->
          <div class="block3">
            <a href="blog-detail.html" class="block3-img dis-block hov-img-zoom">
              <img src="images/news_3.jpg" alt="IMG-BLOG">
            </a>

            <div class="block3-txt p-t-14">
              <h4 class="p-b-7">
                <a href="blog-detail.html" class="m-text11">
                  Cyberpunk 2077 Will Not Be Available on Stadia at Launch
                </a>
              </h4>

              <span class="s-text6">By</span> <span class="s-text7">Pyl Walker ✔</span>
              <span class="s-text6">on</span> <span class="s-text7" id="news-date-1"></span>

              <p class="s-text8 p-t-16">
                Not so instant streaming.
              </p>
            </div>
          </div>
        </div>

        <script type="text/javascript">
          var today = new Date();
          var dd = String(today.getDate()).padStart(2, '0');
          var months = [ "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" ];
          var mm = String(today.getMonth() + 1); //January is 0!
          var yyyy = today.getFullYear();

          today = months[mm - 1] + ' ' + dd + ', ' + yyyy;
          document.getElementById('news-date-1').innerHTML = today;
          document.getElementById('news-date-2').innerHTML = today;
          document.getElementById('news-date-3').innerHTML = today;
        </script>
      </div>
    </div>
  </section>

  <!-- Instagram -->
  <section class="instagram p-t-20">
    <div class="sec-title p-b-52 p-l-15 p-r-15">
      <h3 class="m-text5 t-center">
        @ follow us on Instagram
      </h3>
    </div>

    <div class="flex-w">
      <!-- Block4 -->
      <div class="block4 wrap-pic-w">
        <img src="public/images/gallery-03.jpg" alt="IMG-INSTAGRAM">

        <a href="#" class="block4-overlay sizefull ab-t-l trans-0-4">
          <span class="block4-overlay-heart s-text9 flex-m trans-0-4 p-l-40 p-t-25">
            <i class="icon_heart_alt fs-20 p-r-12" aria-hidden="true"></i>
            <span class="p-t-2">39</span>
          </span>

          <div class="block4-overlay-txt trans-0-4 p-l-40 p-r-25 p-b-30">
            <p class="s-text10 m-b-15 h-size1 of-hidden">
              Nullam scelerisque, lacus sed consequat laoreet, dui enim iaculis leo, eu viverra ex nulla in tellus. Nullam nec ornare tellus, ac fringilla lacus. Ut sit amet enim orci. Nam eget metus elit.
            </p>

            <span class="s-text9">
              Photo by @nancyward
            </span>
          </div>
        </a>
      </div>

      <!-- Block4 -->
      <div class="block4 wrap-pic-w">
        <img src="public/images/gallery-07.jpg" alt="IMG-INSTAGRAM">

        <a href="#" class="block4-overlay sizefull ab-t-l trans-0-4">
          <span class="block4-overlay-heart s-text9 flex-m trans-0-4 p-l-40 p-t-25">
            <i class="icon_heart_alt fs-20 p-r-12" aria-hidden="true"></i>
            <span class="p-t-2">39</span>
          </span>

          <div class="block4-overlay-txt trans-0-4 p-l-40 p-r-25 p-b-30">
            <p class="s-text10 m-b-15 h-size1 of-hidden">
              Nullam scelerisque, lacus sed consequat laoreet, dui enim iaculis leo, eu viverra ex nulla in tellus. Nullam nec ornare tellus, ac fringilla lacus. Ut sit amet enim orci. Nam eget metus elit.
            </p>

            <span class="s-text9">
              Photo by @nancyward
            </span>
          </div>
        </a>
      </div>

      <!-- Block4 -->
      <div class="block4 wrap-pic-w">
        <img src="public/images/gallery-09.jpg" alt="IMG-INSTAGRAM">

        <a href="#" class="block4-overlay sizefull ab-t-l trans-0-4">
          <span class="block4-overlay-heart s-text9 flex-m trans-0-4 p-l-40 p-t-25">
            <i class="icon_heart_alt fs-20 p-r-12" aria-hidden="true"></i>
            <span class="p-t-2">39</span>
          </span>

          <div class="block4-overlay-txt trans-0-4 p-l-40 p-r-25 p-b-30">
            <p class="s-text10 m-b-15 h-size1 of-hidden">
              Nullam scelerisque, lacus sed consequat laoreet, dui enim iaculis leo, eu viverra ex nulla in tellus. Nullam nec ornare tellus, ac fringilla lacus. Ut sit amet enim orci. Nam eget metus elit.
            </p>

            <span class="s-text9">
              Photo by @nancyward
            </span>
          </div>
        </a>
      </div>

      <!-- Block4 -->
      <div class="block4 wrap-pic-w">
        <img src="public/images/gallery-13.jpg" alt="IMG-INSTAGRAM">

        <a href="#" class="block4-overlay sizefull ab-t-l trans-0-4">
          <span class="block4-overlay-heart s-text9 flex-m trans-0-4 p-l-40 p-t-25">
            <i class="icon_heart_alt fs-20 p-r-12" aria-hidden="true"></i>
            <span class="p-t-2">39</span>
          </span>

          <div class="block4-overlay-txt trans-0-4 p-l-40 p-r-25 p-b-30">
            <p class="s-text10 m-b-15 h-size1 of-hidden">
              Nullam scelerisque, lacus sed consequat laoreet, dui enim iaculis leo, eu viverra ex nulla in tellus. Nullam nec ornare tellus, ac fringilla lacus. Ut sit amet enim orci. Nam eget metus elit.
            </p>

            <span class="s-text9">
              Photo by @nancyward
            </span>
          </div>
        </a>
      </div>

      <!-- Block4 -->
      <div class="block4 wrap-pic-w">
        <img src="public/images/gallery-15.jpg" alt="IMG-INSTAGRAM">

        <a href="#" class="block4-overlay sizefull ab-t-l trans-0-4">
          <span class="block4-overlay-heart s-text9 flex-m trans-0-4 p-l-40 p-t-25">
            <i class="icon_heart_alt fs-20 p-r-12" aria-hidden="true"></i>
            <span class="p-t-2">39</span>
          </span>

          <div class="block4-overlay-txt trans-0-4 p-l-40 p-r-25 p-b-30">
            <p class="s-text10 m-b-15 h-size1 of-hidden">
              Nullam scelerisque, lacus sed consequat laoreet, dui enim iaculis leo, eu viverra ex nulla in tellus. Nullam nec ornare tellus, ac fringilla lacus. Ut sit amet enim orci. Nam eget metus elit.
            </p>

            <span class="s-text9">
              Photo by @nancyward
            </span>
          </div>
        </a>
      </div>
    </div>
  </section>

  <!-- Shipping -->
  <section class="shipping bgwhite p-t-62 p-b-46">
    <div class="flex-w p-l-15 p-r-15">
      <div class="flex-col-c w-size5 p-l-15 p-r-15 p-t-16 p-b-15 respon1">
        <h4 class="m-text12 t-center">
          Fast Payment, Support All Banks 🏦
        </h4>

        <a href="#" class="s-text11 t-center">
          Click here for more info
        </a>
      </div>

      <div class="flex-col-c w-size5 p-l-15 p-r-15 p-t-16 p-b-15 bo2 respon2">
        <h4 class="m-text12 t-center">
          24 Hours Refund ⌚
        </h4>

        <span class="s-text11 t-center">
          Simply return it within 24 hours for an exchange.
        </span>
      </div>

      <div class="flex-col-c w-size5 p-l-15 p-r-15 p-t-16 p-b-15 respon1">
        <h4 class="m-text12 t-center">
          Store Opening 🏪
        </h4>

        <span class="s-text11 t-center">
          Shop open all time
        </span>
      </div>
    </div>
  </section>